name: "Prepare Release Action"
description: "An action that can automate release steps and sync them back to the releasing repo."
branding:
  icon: zap
  color: purple

inputs:
  # Required
  version:
    description: "The version of the thing to be released. Must be a semver valid string."
    required: false
    default: ${{ github.event.release.tag_name }}

  # Optional
  bundle-dependencies:
    description: "A toggle to autoset bundleDependencies in package.json."
    required: false
    default: false
  commands:
    description: "A list of commands to run to prepare the release."
    required: false
  lando-plugin:
    description: "A special easy-mode setting to prepare and valdiate Lando plugins."
    required: false
    default: false
  meta:
    description: "A list of path=value strings to merge into the package.json"
    required: false
  root:
    description: "The location of the code being prepared for release."
    required: false
    default: ${{ github.workspace }}
  sync:
    description: "A toggle to enable/disable code syncing."
    required: false
    default: true
  sync-branch:
    description: "The target branch to use when syncing changes back to the repo ."
    required: false
    default: ${{ github.event.release.target_commitish || github.event.pull_request.head.ref || github.ref_name }}
  sync-email:
    description: "The email to use when syncing changes back to the repo."
    required: false
    default: "41898282+github-actions[bot]@users.noreply.github.com"
  sync-message:
    description: "The commit message to use when syncing changes back to the repo."
    required: false
    default: "release v%s generated by @lando/prepare-release-action"
  sync-tags:
    description: "A list of other tags to sync back to the repo."
    required: false
  sync-token:
    description: "A Personal Access Token to use for git sync ops."
    required: true
    default: ${{ github.token }}
  sync-username:
    description: "The username to use when syncing changes back to the repo."
    required: false
    default: "github-actions[bot]"
  update-files:
    description: "The files to operate on with update-files-meta."
    required: false
  update-files-meta:
    description: "The find/replace metadata to be used when updating update-files."
    required: false
  version-match:
    description: "A regex to help find the latest tag. Only used when version=dev."
    required: false
    default: "v[0-9].*"

runs:
  using: "node20"
  main: "dist/index.js"

