'use strict';

const core = require('@actions/core');

module.exports = () => ({
  // required inputs
  version: String(core.getInput('version')),

  // optional inputs
  commands: core.getMultilineInput('commands'),
  landoPlugin: process.env.GITHUB_ACTIONS ? core.getBooleanInput('lando-plugin') : false,
  root: core.getInput('root') || process.cwd(),
  sync: process.env.GITHUB_ACTIONS ? core.getBooleanInput('sync') : false,
  syncBranch: core.getInput('sync-branch') || 'main',
  syncEmail: core.getInput('sync-email') || 'github-actions@github.com',
  syncMessage: core.getInput('sync-message') || 'release %s generated by @lando/prepare-release-action',
  syncTags: core.getMultilineInput('sync-tags'),
  syncUsername: core.getInput('sync-username') || 'github-actions',
});
