'use strict';

const core = require('@actions/core');

module.exports = () => ({
  // required inputs
  version: String(core.getInput('version')),

  // optional inputs
  bundleDependencies: process.env.GITHUB_ACTIONS ? core.getBooleanInput('bundle-dependencies') : false,
  commands: core.getMultilineInput('commands'),
  credFiles: [],
  landoPlugin: process.env.GITHUB_ACTIONS ? core.getBooleanInput('lando-plugin') : false,
  meta: core.getMultilineInput('meta'),
  root: core.getInput('root') || process.cwd(),
  sync: process.env.GITHUB_ACTIONS ? core.getBooleanInput('sync') : false,
  syncBranch: core.getInput('sync-branch') || 'main',
  syncEmail: core.getInput('sync-email') || 'github-actions@github.com',
  syncMessage: core.getInput('sync-message') || 'release v%s generated by @lando/prepare-release-action',
  syncTags: core.getMultilineInput('sync-tags'),
  syncToken: core.getInput('sync-token') || process.env.GITHUB_TOKEN,
  syncUsername: core.getInput('sync-username') || 'github-actions',
  tokens: core.getMultilineInput('update-files-meta') ?? [],
  updateHeader: core.getMultilineInput('update-files-header') ?? [],
  updateFiles: core.getMultilineInput('update-files') ?? [],
  versionMatch: core.getInput('version-match') || 'v[0-9].*',
});
