name: Basic Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      term: xterm
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        version:
          - v0.0.1-riker.1
          - 1.0.0-beta.1
          - dev
        bundle-dependencies:
          - true
          - false
        node-version:
          - '20'
        lando-plugin:
          - true
          - false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install deps and prep
        run: |
          npm clean-install
          npm run prepare
      - name: Export release date
        run: |
          date -d "2013-02-27T19:35:32Z" "+%B%e, %Y"
          echo "RELEASE_DATE=$(date "+%B%e, %Y")" >> $GITHUB_ENV
      - name: Prepare release
        uses: ./
        with:
          version: ${{ matrix.version }}
          bundle-dependencies: ${{ matrix.bundle-dependencies }}
          commands: npm run prepare
          lando-plugin: ${{ matrix.lando-plugin }}
          sync-tags: |
            v2
            kirk-epsilon
          sync: false
          update-files: CHANGELOG.md
          update-files-header: |
            ## {{ UNRELEASED_VERSION }} - [{{ UNRELEASED_DATE }}]({{ UNRELEASED_LINK }})

          update-files-meta: |
            UNRELEASED_DATE=${{ env.RELEASE_DATE }}
            UNRELEASED_LINK=${{ github.repositoryUrl }}
            UNRELEASED_VERSION=v${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt}}-build.${{ github.sha }}
