name: Lint Code

on:
  pull_request:

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        node-version:
          - '20'

    steps:
      # Install deps and cache
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PIROG_TOKEN }}
          fetch-depth: 0

      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: debug
        run: |
          npm clean-install
          npm run prepare
          cat ./.git/config


