name: Sync Tests

on:
  pull_request:

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        node-version:
          - '20'

    steps:
      # Install deps and cache
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Prepare release
        uses: ./
        with:
          version: dev
          commands: |
            touch riker
            touch picard
            git pull origin main
          lando-plugin: false
          meta: |
            jazzman=William T. Riker
            bosmang=Picard
          root: ${{ github.workspace }}
          sync: true
          sync-branch: test
          sync-email: william.t.riker@starfleet.mil
          sync-message: riker
          sync-tags: number1
          sync-token: ${{ secrets.PIROG_TOKEN }}
          sync-username: Will
