name: Sync Tests

on:
  # pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        node-version:
          - '20'

    steps:
      # Install deps and cache
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Prepare release
        uses: ./
        with:
          version: v3.1.0
          # commands: |
          #   touch riker
          #   touch picard
          lando-plugin: false
          # meta: |
          #   jazzman=William T. Riker
          #   bosmang=Picard
          # root: ${{ github.workspace }}
          sync: true
          sync-branch: main
          sync-email: william.t.riker@starfleet.mil
          sync-message: riker
          sync-tags: number1
          sync-username: Will
